---
- name: Notify approver about the VM snapshot and request for approve.
  hosts: localhost
  #become: yes
  #become_user: root
  gather_facts: false

  tasks:
    - name: Send email with status
      community.general.mail:
        host: "smtp.federalbank.co.in"
        port: 25 # Or your SMTP port, commonly 465 for SSL/TLS
        #username: "noreply_ansible@federalbank.co.in"
        sender: ritwik@federalbank.co.in
        to: 
          - ritwik@federalbank.co.in
        subject: "Ansible Test"
        body: " Hello"
        # secure: starttls # Or 'always', 'never', 'try' depending on your SMTP server
      #delegate_to: localhost
